CREATE DATABASE LABORATORIO_VIRTUAL
GO
USE LABORATORIO_VIRTUAL
GO
CREATE TABLE INVENTARIO (
	ID INT IDENTITY(1,1),
	CODIGO_DE_REPUESTO VARCHAR(4) NOT NULL,
	NOMBRE_DEL_REPUESTO VARCHAR(100) NOT NULL,
	MARCA_DEL_REPUESTO VARCHAR(100) NOT NULL,
	VEHICULO VARCHAR(100) NOT NULL,
	MODELO VARCHAR (100) NOT NULL,
	ANIO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	FECHA_DE_REGISTRO DATETIME NOT NULL,
	FECHA_DE_MODIFICACION DATETIME,
	ESTADO BIT NOT NULL
)